/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/models/IsometricBedroomOnlyTexturesNoMaterial.glb 
*/
import React from 'react'
import { useGLTF } from '@react-three/drei'

export function BedroomBaked(props) {
	const { nodes, materials } = useGLTF('src/assets/models/IsometricBedroomOnlyTexturesNoMaterial.glb')
  
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.Window_Frame.geometry} material={materials['Window Frame White']} position={[0.391, 1.24, -1.052]} />
			<group position={[0.402, 1.463, -1.041]}>
				<mesh geometry={nodes.Cube015.geometry} material={materials.Shade} />
				<mesh geometry={nodes.Cube015_1.geometry} material={materials['Shade White']} />
			</group>
			<group position={[0.391, 0.952, -1.043]}>
				<mesh geometry={nodes.Cube012.geometry} material={materials['Windows Light']} />
				<mesh geometry={nodes.Cube012_1.geometry} material={materials.Window} />
			</group>
			<mesh geometry={nodes.Upper_Window_Emission.geometry} material={materials['Windows Light']} position={[0.391, 1.24, -1.186]} />
			<mesh geometry={nodes.Upper_Window.geometry} material={materials.Window} position={[0.391, 1.24, -1.186]} />
			<mesh geometry={nodes.Bed.geometry} material={materials.Bed} position={[0.545, 0.128, -0.325]} />
			<mesh geometry={nodes.Pillow_1.geometry} material={materials['Pillow Orange']} position={[0.556, 0.338, -0.717]} rotation={[0.412, 0, 0]} />
			<mesh geometry={nodes.Pillow_2.geometry} material={materials['Pillow Yellow']} position={[0.759, 0.315, -0.497]} rotation={[0.242, -0.353, -0.024]} />
			<mesh geometry={nodes.Matress.geometry} material={materials.Matress} position={[0.545, 0.219, -0.267]} />
			<mesh geometry={nodes.Sheets.geometry} material={materials.Sheets} position={[0.545, 0.219, -0.267]} />
			<group position={[-0.132, 0.639, 0.433]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
				<mesh geometry={nodes.Cylinder014.geometry} material={materials['Camera Black']} />
				<mesh geometry={nodes.Cylinder014_1.geometry} material={materials['Camera Lens']} />
				<mesh geometry={nodes.Cylinder014_2.geometry} material={materials['Camera Screen']} />
				<mesh geometry={nodes.Cylinder014_3.geometry} material={materials['Lens Ring']} />
				<mesh geometry={nodes.Cylinder014_4.geometry} material={materials['Camera Btn Red']} />
			</group>
			<group position={[-0.057, 0.581, 0.426]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
				<mesh geometry={nodes.Circle009.geometry} material={materials['Camera Tripod Black']} />
				<mesh geometry={nodes.Circle009_1.geometry} material={materials['Camera Tripod Grey']} />
			</group>
			<mesh geometry={nodes.Teclado.geometry} material={materials['Desk Keyboard']} position={[-0.5, 0.471, -0.659]} />
			<mesh geometry={nodes.Mouse_Pad.geometry} material={materials['Mouse Pad']} position={[-0.499, 0.455, -0.68]} />
			<mesh geometry={nodes.Mug.geometry} material={materials.Mug} position={[-0.096, 0.482, -0.75]} rotation={[0, Math.PI / 3, 0]} />
			<mesh geometry={nodes.Mouse.geometry} material={materials['Mouse Black']} position={[-0.329, 0.464, -0.66]}>
				<mesh geometry={nodes.Mouse_Whell.geometry} material={nodes.Mouse_Whell.material} position={[0, 0, -0.015]} rotation={[0, 0, -Math.PI / 2]} />
			</mesh>
			<group position={[-0.501, 0.441, -0.757]}>
				<mesh geometry={nodes.Plane009.geometry} material={materials['Desk Black']} />
				<mesh geometry={nodes.Plane009_1.geometry} material={materials['LED Mesa']} />
			</group>
			<mesh geometry={nodes.Desk_Lamp.geometry} material={materials['Desk Lamp']} position={[-0.837, 0.624, -0.883]} rotation={[1.292, -Math.PI / 2, 0]} />
			<group position={[-0.5, 0.637, -0.838]}>
				<mesh geometry={nodes.Cube007.geometry} material={materials.Screen} />
				<mesh geometry={nodes.Cube007_1.geometry} material={materials['Monitor Black']} />
			</group>
			<group position={[-0.85, 0.091, 0.365]} rotation={[Math.PI / 6, 0, 0]}>
				<mesh geometry={nodes.Cylinder.geometry} material={materials['Green Screen Tripod']} />
				<mesh geometry={nodes.Cylinder_1.geometry} material={materials['Green Screen']} />
			</group>
			<mesh geometry={nodes.Pegboard.geometry} material={materials.PegBoard} position={[-1.011, 1.097, -0.688]} />
			<mesh geometry={nodes.HeadPhone.geometry} material={materials['Headphone Black']} position={[-0.942, 1.253, -0.745]} rotation={[0, 0, -Math.PI / 2]} />
			<mesh geometry={nodes.Controller.geometry} material={materials['Controler Black']} position={[-0.978, 1.031, -0.57]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
			<group position={[-0.958, 1.025, -0.759]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
				<mesh geometry={nodes.Cube021.geometry} material={materials['Peg Keyboard White']} />
				<mesh geometry={nodes.Cube021_1.geometry} material={materials['Peg Keyboard Black']} />
				<mesh geometry={nodes.Cube021_2.geometry} material={materials['Peg Keyboard Orange']} />
			</group>
			<mesh geometry={nodes.Rodapé.geometry} material={materials.Rodape} position={[-0.171, 0.829, -0.171]} />
			<mesh geometry={nodes.Walls.geometry} material={materials.Walls} position={[-0.07, 0.93, -0.07]} />
			<mesh geometry={nodes.Rug.geometry} material={materials.Rug} position={[0.309, 0.012, 0.553]} />
			<mesh geometry={nodes.Floor_1.geometry} material={materials['Floor Color 3']} position={[0, 0, 0.023]} />
			<mesh geometry={nodes.Floor_3.geometry} material={materials['Floor Color 1']} position={[0, 0, 0.02]} />
			<mesh geometry={nodes.Floor_2.geometry} material={materials['Floor Color 2']} position={[0, 0, 0.023]} />
			<mesh geometry={nodes.Chair.geometry} material={materials.Chair} position={[-0.722, 0.394, -0.417]} rotation={[Math.PI, -1.065, Math.PI]} />
			<mesh geometry={nodes.Painting_Frames.geometry} material={materials['Paintings Frame White']} position={[-0.338, 1.119, -1]} />
			<mesh geometry={nodes.Okami.geometry} material={materials.Okami} position={[-0.337, 1.124, -0.982]} rotation={[Math.PI / 2, 0, 0]} />
			<mesh geometry={nodes['Studio-Ghibli-Logo'].geometry} material={materials['Studio-Ghibli-Logo']} position={[-0.717, 1.002, -0.982]} rotation={[Math.PI / 2, 0, 0]} />
			<mesh geometry={nodes['cowboy-bebop'].geometry} material={materials['cowboy-bebop']} position={[-0.717, 1.235, -0.982]} rotation={[Math.PI / 2, 0, 0]} />
		</group>
	)
}

useGLTF.preload('src/assets/models/IsometricBedroomOnlyTexturesNoMaterial.glb')
